// Syncs per-platform store versions from app_version.yaml into:
//   android/app/version.properties   (read by android/app/build.gradle.kts)
//   ios/Flutter/AppVersion.xcconfig  (included by Debug/Release.xcconfig)
//
// Usage (from mobile/): dart run tool/sync_app_version.dart
import 'dart:io';

final _namePattern = RegExp(r'^\d+\.\d+\.\d+$');

void main() {
  final root = File.fromUri(Platform.script).parent.parent;
  final source = File('${root.path}/app_version.yaml');
  if (!source.existsSync()) {
    _fail('Missing ${source.path}');
  }

  final versions = _parse(source.readAsLinesSync());
  final android = _require(versions, 'android');
  final ios = _require(versions, 'ios');

  File('${root.path}/android/app/version.properties').writeAsStringSync(
    '# Generated by tool/sync_app_version.dart from app_version.yaml — do not edit.\n'
    'versionName=${android.name}\n'
    'versionCode=${android.code}\n',
  );

  File('${root.path}/ios/Flutter/AppVersion.xcconfig').writeAsStringSync(
    '// Generated by tool/sync_app_version.dart from app_version.yaml — do not edit.\n'
    'FLUTTER_BUILD_NAME=${ios.name}\n'
    'FLUTTER_BUILD_NUMBER=${ios.code}\n',
  );

  stdout
    ..writeln('android: ${android.name} (${android.code})')
    ..writeln('ios:     ${ios.name} (${ios.code})');
}

class _Version {
  _Version(this.name, this.code);
  final String name;
  final int code;
}

Map<String, Map<String, String>> _parse(List<String> lines) {
  final result = <String, Map<String, String>>{};
  String? section;
  for (final raw in lines) {
    final line = raw.split('#').first.trimRight();
    if (line.trim().isEmpty) continue;
    final indented = line.startsWith(' ') || line.startsWith('\t');
    final parts = line.trim().split(':');
    if (parts.length < 2) _fail('Invalid line: "$raw"');
    final key = parts.first.trim();
    final value = parts.sublist(1).join(':').trim();
    if (!indented) {
      section = key;
      result[section] = {};
    } else if (section == null) {
      _fail('Indented key "$key" outside of a section');
    } else {
      result[section]![key] = value.replaceAll(RegExp('^["\']|["\']\$'), '');
    }
  }
  return result;
}

_Version _require(Map<String, Map<String, String>> versions, String platform) {
  final entry = versions[platform];
  if (entry == null) _fail('Missing "$platform" section');
  final name = entry['name'];
  final code = int.tryParse(entry['code'] ?? '');
  if (name == null || !_namePattern.hasMatch(name)) {
    _fail('$platform.name must look like 1.2.3 (got "$name")');
  }
  if (code == null || code < 1) {
    _fail('$platform.code must be a positive integer (got "${entry['code']}")');
  }
  return _Version(name, code);
}

Never _fail(String message) {
  stderr.writeln('sync_app_version: $message');
  exit(1);
}
